[package]
name = "alarm"
version = "0.1.0"
authors = ["László Vaskó <laszlo.vasko@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
docopt = "1"
num-traits = "0.2"
num-derive = "0.2"